# Generated by Django 4.1.1 on 2024-03-20 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coffeeapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
    ]
